#--------------------------------------------------------------------------------#
# Paths included/excluded
#--------------------------------------------------------------------------------#
included:    # paths to include during linting. `--path` is ignored if present.
  - AROrganizer
  - XCodeTemplates
  - Resources
excluded:    # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
#--------------------------------------------------------------------------------#
# Rules
#--------------------------------------------------------------------------------#
# Find all the available rules by running:
# swiftlint rules
#--------------------------------------------------------------------------------#
disabled_rules: # rule identifiers to exclude from running
  - colon
  #- comma
  #- control_statement
  - trailing_whitespace
  - identifier_name
  #- cyclomatic_complexity
  - function_body_length
opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
  - weak_delegate
  - closure_spacing
  - collection_alignment
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - operator_usage_whitespace
  - unused_import
  - array_init
  - overridden_super_call
  #- vertical_whitespace_between_cases
  #- vertical_whitespace_closing_braces
  #- vertical_whitespace_opening_braces
  #- force_unwrapping
  #- private_outlet
  #- missing_docs
#--------------------------------------------------------------------------------#
# Other
#--------------------------------------------------------------------------------#
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
#  - explicit_self

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
#--------------------------------------------------------------------------------#
# File lengths
#--------------------------------------------------------------------------------#
file_length:  # naming rules can set warnings/errors for min_length and max_length
  warning: 500
  error: 1200

line_length:
  warning: 165
  error: 2500

function_parameter_count:
warning: 10
error: 15

type_body_length:
warning: 400
error: 450

cyclomatic_complexity:
warning: 15
error: 25
#--------------------------------------------------------------------------------#
# Part of File
#--------------------------------------------------------------------------------#
type_body_length:
  - 300 # warning
  - 400 # error

type_name:
  min_length: 3   # only warning
  max_length:
    warning: 40
    error: 50
  excluded:
  - iPhone       # excluded via string
  - id
  - ad
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length:
    error: 2

excluded: # excluded via string array
    - id
    - URL
    
#--------------------------------------------------------------------------------#
# Show messages
#--------------------------------------------------------------------------------#
reporter: "xcode"
